config/routes.rb
GenomespaceNew::Application.routes.draw do
 
	mount Ckeditor::Engine => "/ckeditor"
	resources :server_properties
	match "sites/genomespacefiles/config/serverurl.properties" => "site#server_properties", :as => "view_server_properties"
	match "system-status/urgent(.format)" => "site#view_urgent_system_messages", :as => "view_urgent_system_messages"
	match "system-status/latest(.format)" => "site#view_system_message"
	match "system-status/:url" => "site#view_system_message", :as => "view_system_message", :constraints => {:url => /.*/} 
	match "system-status" => "site#view_system_messages", :as => "view_system_messages", :constraints => {:url => /.*/} 
  resources :system_messages

	post "slideshow_items/reorder_slideshow_items" => "slideshow_items#reorder_slideshow_items"
  resources :slideshow_items
  get "request_invite" => "site#request_invite", :as => "request_invite"
  post "request_invite" => "site#process_invite", :as => "process_invite"
  get "request_received" => "site#request_received", :as => "request_received"
  match "invites/send_registration_invite/:id" => "invites#send_registration_invite", :as => "send_registration_invite"
  post "invites/bulk_invites" => "invites#bulk_invites", :as => "bulk_invites"
  resources :invites

  match "pages/:id/show_revisions" => "pages#show_revisions", :as => "show_revisions"
	match "pages/:id/revert_revision/:version" => "pages#revert_revision", :as => "revert_revision"
  match "pages/diff_content/:id/revision/:revision" => "pages#diff_content", :as => "diff_page_content"
  resources :pages
  
  get "menu_items" => "menu_items#index", :as => "menu_items"
  post "reorder_menu_items/:category" => "menu_items#reorder_menu_items"
  
  resources :deliverables
  resources :tools
  
  match "guides/:guide_id/guide_sections/:id/show_revisions" => "guide_sections#show_revisions", :as => "show_guide_section_revisions"
  match "guides/:guide_id/guide_sections/:id/revert_revision/:version" => "guide_sections#revert_revision", :as => "revert_guide_section_revisions"
  match "guides/:guide_id/guide_sections/diff_content/:id/revision/:revision" => "guide_sections#diff_content", :as => "diff_guide_section_content"
  resources :guides do
  	resources :guide_sections
 		post "reorder_guide_sections" => "guide_sections#reorder_guide_sections"
 		post "nest_guide_section/:id" => "guide_sections#nest_guide_section"
 		post "denest_guide_section/:id" => "guide_sections#denest_guide_section"
  end
  
  match "docs/:id/show_revisions" => "docs#show_revisions", :as => "show_doc_revisions"
  match "docs/:id/revert_revision/:version" => "docs#revert_revision", :as => "revert_doc_revision"
  resources :docs
  match "docs/new/copy" => "docs#new", :as => "copy_doc"
  match "docs/diff_content/:id/revision/:revision" => "docs#diff_content", :as => "diff_doc_content"
	
	match "blog/report_abuse/:id" => "site#report_abuse", :as => "report_abuse"
	get "blog(/:url)" => "site#view_blog", :as => "view_blog", :constraints => {:url => /.*/} 
	match "latest_news" => "site#latest_news", :as => "latest_news"
	resources :posts
	
	resources :highlights
	match "news(/:url)" => "site#view_highlights", :as => "view_highlights"
	
  devise_for :users
  resources :users
    
  match "replace_selected_item/:id" => "site#replace_selected_item", :as => "replace_selected_item" 
  match "get_other_slideshow_items/:offset" => "site#get_other_slideshow_items", :as => "get_other_slideshow_items"
  match "team" => "site#team", :as => "team"
  match "team/deliverables" => "site#deliverables", :as => "view_deliverables"
  get "team/deliverables_report/:quarter" => "site#deliverables_report", :as => "view_deliverables_report"
  post "team/deliverables_report/:quarter" => "site#process_deliverables_report", :as => "process_deliverables_report"
  get "register" => "site#register", :as => "register_account"
  post "register" => "site#process_registration", :as => "process_registration"
  get "support" => "site#support", :as => "support"
  post "support" => "site#genomespace_google_groups", :as => "support_google_groups"
 	post "support/api/:url" => "site#view_docs"
 	match "support/api/:url(?:rev=:version)" => "site#view_docs"
 	match "support/guides/:url/print" => "site#print_guide", :as => "print_guide"
 	match "recipes" => redirect("/support/guides/recipes")
 	match "support/guides/:url" => "site#view_guide"
 	match "support/guides/:url/sections/:display_url(?:rev=:version)" => "site#view_guide"
 	match "support/guides/:url/sections/:display_url/instructions" => "site#recipe_instructions"
 	match "support/tools(/:lookup_name)" => "site#tools", :as => "view_tools"
 	match "search" => "site#search", :as => "search"
 	match "search/google/:search" => "site#google_search", :as => "google_search"
 	post "route_action" => "application#route_action", :as => "route_action"
  match "admin" => "application#admin", :as => "admin"
  match "/:url(?:rev=:version)" => "site#view" 
  get "/" => "site#index", :as => "site"
  root :to => "site#index"
  match "*a" => "site#rescue_from_nil_page", :constraints => lambda{|req| req.env["REQUEST_PATH"] !~ /(ckeditor|assets)/ }

end

app/models/invite.rb
class Invite < ActiveRecord::Base

	attr_accessible :email, :sent_invite, :created_at, :updated_at, :emailed

	def display_date
		return self.created_at.strftime("%B %d, %Y at %I:%M%P")
	end
	
	def email_display_date
		return self.emailed.strftime("%B %d, %Y at %I:%M%P")
	end
	
	def self.admin_description
		return "<font color='red'>Invites are deprecated and no longer in use</font>."
	end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  
  layout "admin"
  
  before_filter do 
  	authenticate_user!
  	authenticate_cms_admin
  end
  
  # GET /invites
  # GET /invites.json
  def index
    @invites = Invite.all
    @sent = Invite.find_all_by_sent_invite(true).count
    @unsent = Invite.find_all_by_sent_invite(false).count

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invites }
    end
  end

  # GET /invites/1
  # GET /invites/1.json
  def show
    @invite = Invite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invite }
    end
  end

  # GET /invites/new
  # GET /invites/new.json
  def new
    @invite = Invite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invite }
    end
  end

  # GET /invites/1/edit
  def edit
    @invite = Invite.find(params[:id])
  end

  # POST /invites
  # POST /invites.json
  def create
    @invite = Invite.new(params[:invite])

    respond_to do |format|
      if @invite.save
        format.html { redirect_to @invite, notice: "Invite for #{@invite.email} was successfully created." }
        format.json { render json: @invite, status: :created, location: @invite }
      else
        format.html { render action: "new" }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invites/1
  # PUT /invites/1.json
  def update
    @invite = Invite.find(params[:id])

    respond_to do |format|
      if @invite.update_attributes(params[:invite])
        format.html { redirect_to @invite, notice: "Invite for #{@invite.email}was successfully updated." }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  def destroy
    @invite = Invite.find(params[:id])
    @invite.destroy

    respond_to do |format|
      format.html { redirect_to invites_url }
      format.json { head :ok }
    end
  end
  
  def send_registration_invite
  	@invite = Invite.find(params[:id])
  	GenomespaceMailer.send_registration_invitation(@invite).deliver
  	@invite.sent_invite = true
  	@invite.emailed = Time.now.to_s
  	@invite.save
  	
  	redirect_to invites_path, notice: "You have sent a registration invitation to #{@invite.email}."
  end
  
  def bulk_invites
    	
  	@invites_to_send = params[:send_bulk].keep_if{|k,v|v=="1"}.keys
  	@sent = Array.new
  	
  	@invites_to_send.each do |i|
  		invite = Invite.find(i)
  		GenomespaceMailer.send_registration_invitation(invite).deliver
  		@sent << invite.email
  		invite.sent_invite = true
  		invite.emailed = Time.now.to_s
  		invite.save
  	end
  	redirect_to invites_path, notice: "Registration invitations were sent to #{@sent}."
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_form.html.erb
<%= form_for(@invite) do |f| %>
  <% if @invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

      <ul>
      <% @invite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
    <%= f.hidden_field :sent_invite, :value => false %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invites/edit.html.erb
<h1>Editing invite</h1>

<%= render 'form' %>

<%= link_to 'Show', @invite %> |
<%= link_to 'Back', invites_path %>

app/views/invites/index.html.erb
<h1>GenomeSpace Registration Invites <span style="color: #212">[Pending: <span style="color:red;"><%= @unsent %></span>, Sent: <span style="color:green;"><%= @sent %></span>]</span></h1>
<%= form_for :bulk_invites, {:url => bulk_invites_path} do %>
	<table id="pages">
	<thead>
	  <tr>
	  	<th></th>
	    <th>Email</th>
	    <th>Recieved On</th>
	    <th>Sent Invite?</th>
	    <th>Email Sent On</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	</thead>
	<tbody>
		<% @invites.each do |invite| %>
		  <tr>
		  	<td><%= check_box(:send_bulk, invite.id) %></td>
		    <td><%= invite.email %></td>
		    <td><%= invite.display_date %></td>
		    <td><%= invite.sent_invite? ? "Yes" : "No" %></td>
		    <td><%= invite.sent_invite? ? invite.email_display_date : "N/A" %></td>
		    <td><%= link_to 'Send Email to User', send_registration_invite_path(invite), confirm: "Would you like to send a registration invitation to #{invite.email}?" %></td>
		    <td><%= link_to 'Edit', edit_invite_path(invite) %></td>
		    <td><%= link_to 'Destroy', invite, confirm: 'Are you sure?', method: :delete %></td>
		  </tr>
		<% end %>
	</tbody>
	</table>
	<br />
	<table border="0"><tr><td>
	Bulk Emails: <%= button_to_function "Toggle All Visible", "toggleChecked()" %></td><td>
	<%= submit_tag "Email All Checked", confirm: "Would you like to send registration invitations to all of the checked emails?" %></td></tr></table>
<% end %>
<%= button_to 'New Invitation', new_invite_path, { :method => "get" } %>

<%= javascript_tag do %>

	$(document).ready(function() {
	    oTable = $('#pages').dataTable({
	        "bJQueryUI": true,
	        "sPaginationType": "full_numbers",
	        "aaSorting": [[3, "asc"],[2, "asc"]]
	        
	    });
	} );
	
	var toggleChecked = function() { $('input[type="checkbox"]').click(); };

<% end %>

app/views/invites/new.html.erb
<h1>New invite</h1>

<%= render 'form' %>

<%= link_to 'Back', invites_path %>

app/views/invites/show.html.erb
<p>
  <b>Email:</b>
  <%= @invite.email %>
</p>

<p>
  <b>Sent invite:</b>
  <%= @invite.sent_invite %>
</p>


<%= link_to 'Edit', edit_invite_path(@invite) %> |
<%= link_to 'Back', invites_path %>