config/routes.rb
GenomespaceNew::Application.routes.draw do
 
	mount Ckeditor::Engine => "/ckeditor"
	resources :server_properties
	match "sites/genomespacefiles/config/serverurl.properties" => "site#server_properties", :as => "view_server_properties"
	match "system-status/urgent(.format)" => "site#view_urgent_system_messages", :as => "view_urgent_system_messages"
	match "system-status/latest(.format)" => "site#view_system_message"
	match "system-status/:url" => "site#view_system_message", :as => "view_system_message", :constraints => {:url => /.*/} 
	match "system-status" => "site#view_system_messages", :as => "view_system_messages", :constraints => {:url => /.*/} 
  resources :system_messages

	post "slideshow_items/reorder_slideshow_items" => "slideshow_items#reorder_slideshow_items"
  resources :slideshow_items
  get "request_invite" => "site#request_invite", :as => "request_invite"
  post "request_invite" => "site#process_invite", :as => "process_invite"
  get "request_received" => "site#request_received", :as => "request_received"
  match "invites/send_registration_invite/:id" => "invites#send_registration_invite", :as => "send_registration_invite"
  post "invites/bulk_invites" => "invites#bulk_invites", :as => "bulk_invites"
  resources :invites

  match "pages/:id/show_revisions" => "pages#show_revisions", :as => "show_revisions"
	match "pages/:id/revert_revision/:version" => "pages#revert_revision", :as => "revert_revision"
  match "pages/diff_content/:id/revision/:revision" => "pages#diff_content", :as => "diff_page_content"
  resources :pages
  
  get "menu_items" => "menu_items#index", :as => "menu_items"
  post "reorder_menu_items/:category" => "menu_items#reorder_menu_items"
  
  resources :deliverables
  resources :tools
  
  match "guides/:guide_id/guide_sections/:id/show_revisions" => "guide_sections#show_revisions", :as => "show_guide_section_revisions"
  match "guides/:guide_id/guide_sections/:id/revert_revision/:version" => "guide_sections#revert_revision", :as => "revert_guide_section_revisions"
  match "guides/:guide_id/guide_sections/diff_content/:id/revision/:revision" => "guide_sections#diff_content", :as => "diff_guide_section_content"
  resources :guides do
  	resources :guide_sections
 		post "reorder_guide_sections" => "guide_sections#reorder_guide_sections"
 		post "nest_guide_section/:id" => "guide_sections#nest_guide_section"
 		post "denest_guide_section/:id" => "guide_sections#denest_guide_section"
  end
  
  match "docs/:id/show_revisions" => "docs#show_revisions", :as => "show_doc_revisions"
  match "docs/:id/revert_revision/:version" => "docs#revert_revision", :as => "revert_doc_revision"
  resources :docs
  match "docs/new/copy" => "docs#new", :as => "copy_doc"
  match "docs/diff_content/:id/revision/:revision" => "docs#diff_content", :as => "diff_doc_content"
	
	match "blog/report_abuse/:id" => "site#report_abuse", :as => "report_abuse"
	get "blog(/:url)" => "site#view_blog", :as => "view_blog", :constraints => {:url => /.*/} 
	match "latest_news" => "site#latest_news", :as => "latest_news"
	resources :posts
	
	resources :highlights
	match "news(/:url)" => "site#view_highlights", :as => "view_highlights"
	
  devise_for :users
  resources :users
    
  match "replace_selected_item/:id" => "site#replace_selected_item", :as => "replace_selected_item" 
  match "get_other_slideshow_items/:offset" => "site#get_other_slideshow_items", :as => "get_other_slideshow_items"
  match "team" => "site#team", :as => "team"
  match "team/deliverables" => "site#deliverables", :as => "view_deliverables"
  get "team/deliverables_report/:quarter" => "site#deliverables_report", :as => "view_deliverables_report"
  post "team/deliverables_report/:quarter" => "site#process_deliverables_report", :as => "process_deliverables_report"
  get "register" => "site#register", :as => "register_account"
  post "register" => "site#process_registration", :as => "process_registration"
  get "support" => "site#support", :as => "support"
  post "support" => "site#genomespace_google_groups", :as => "support_google_groups"
 	post "support/api/:url" => "site#view_docs"
 	match "support/api/:url(?:rev=:version)" => "site#view_docs"
 	match "support/guides/:url/print" => "site#print_guide", :as => "print_guide"
 	match "recipes" => redirect("/support/guides/recipes")
 	match "support/guides/:url" => "site#view_guide"
 	match "support/guides/:url/sections/:display_url(?:rev=:version)" => "site#view_guide"
 	match "support/guides/:url/sections/:display_url/instructions" => "site#recipe_instructions"
 	match "support/tools(/:lookup_name)" => "site#tools", :as => "view_tools"
 	match "search" => "site#search", :as => "search"
 	match "search/google/:search" => "site#google_search", :as => "google_search"
 	post "route_action" => "application#route_action", :as => "route_action"
  match "admin" => "application#admin", :as => "admin"
  match "/:url(?:rev=:version)" => "site#view" 
  get "/" => "site#index", :as => "site"
  root :to => "site#index"
  match "*a" => "site#rescue_from_nil_page", :constraints => lambda{|req| req.env["REQUEST_PATH"] !~ /(ckeditor|assets)/ }

end

app/models/doc.rb
class Doc < ActiveRecord::Base

	attr_accessible :component, :maj_version, :min_version, :dev_stage, :url, :contents, :created_at, :updated_at,
									:created_by, :updated_by, :delta, :deprecated, :dev, :lock_version

	versioned :if => Proc.new {|doc| doc.component_changed? || doc.dev_stage_changed? || doc.maj_version_changed? || doc.min_version_changed? || doc.contents_changed? }
	
	validates_presence_of :component, :maj_version, :min_version, :contents
	
	validates_uniqueness_of :url
	
	before_validation  :create_url
	
	before_save :fix_ckeditor_attachment_paths
	
	def self.admin_description
		return "Docs are html objects that are technical documentation for various GenomeSpace APIs or features (called a component in the database).  Each component can have multiple versions and development stages that exist independently of each other (i.e. beta 1.0, beta 2.0, prod 1.1, etc.).  Users can see each version of a given component on the live site by using a dropdown at the top of the page."
	end
		
	# checks to see if there is a revisions specified in the url and reloads if necessary.  Returns an alert as well if user is not signed in.
	def check_version(params, user_signed_in)
		
		if params[:rev] && user_signed_in == true
			self.revert_to(params[:rev].to_i)
			@alert = ""
		elsif params[:rev] && user_signed_in == false
			@alert = "You need to be logged in to view previous revisions of this doc.  Please <a href=\"/users/sign_in\">log in</a> first."
		end
	
		return self, @alert
	end
	
	# creates a new url from the existing and increments indicated version number.  if url has been too customized, appends numbers on the end.
	def new_version_url(version)
		url_parts = self.url.split("-")
		unless url_parts.size < 3
			case version
			when "major"
				url_parts[url_parts.size - 2] = self.maj_version += 1
			when "minor" 
				url_parts[url_parts.size - 1] = self.min_version += 1
			end
		else
			case version
			when "major"
				url_parts.push(self.maj_version += 1, self.min_version)
			when "minor" 
				url_parts.push(self.maj_version, self.min_version += 1)
			end
		end
		return url_parts.join("-")
	end
	
	# returns an array of docs that consists of the latest versions of each available component
	def self.get_latest_components
	
		@docs = []
	
		@components = Doc.all.collect(&:component).uniq
		@components.each do |component|
			doc = Doc.find_all_by_component(component).sort{|x,y| x.get_version <=> y.get_version}.last
			unless doc.deprecated? 
				@docs << doc
			end
		end
		
		return @docs.sort {|x,y| x.component <=> y.component}
		
	end
	
	# return complete version number in standard decimal format, e.g. "beta 3.1" or "2.0"
	def get_version
		self.dev_stage.blank? ? dev_stage_string = "" : dev_stage_string = self.dev_stage + " "
		return dev_stage_string + self.maj_version.to_s + "." + self.min_version.to_s
	end
	
	def get_last_live
	
		@requested_doc = Doc.find(self.id)	
		while @requested_doc.dev == true
			# gotcha for when all revisions of a doc are dev, so return the previous version (beta 1.1 vs. beta 1.2)
			if @requested_doc.dev == true && @requested_doc.version == 1
				@all_versions = Doc.find_all_by_component(@requested_doc.component).sort{|x,y| x.get_version <=> y.get_version}.reverse
				@all_versions.delete_if {|d| d.get_version >= @requested_doc.get_version}
				@requested_doc = @all_versions.first
			else
				@requested_doc.revert_to(@requested_doc.version - 1)
			end
		end
		return @requested_doc	
	end
	
	def self.get_latest_version(url)
	
		return Doc.find_by_sql("SELECT * from docs where url LIKE '#{url}%'").sort{|x,y| x.get_version <=> y.get_version}.last
	
	end
	
	def plain_content
		Hpricot(self.contents).to_plain_text
	end
	
	private
	
	# create a url for a doc using the component, version and dev stage, e.g. "atm-beta-3-1"
	def create_url
		if self.url.blank?
			self.dev_stage.blank? ? dev_stage_string = "" : dev_stage_string = "-" + self.dev_stage + "-"
			component_string = self.component.downcase.gsub(/[^a-zA-Z0-9]+/, "-").chomp("-")
			version_string = self.maj_version.to_s + "-" + self.min_version.to_s
			self.url = component_string + dev_stage_string + version_string
		end
	end 
	
	# to fix bug with hrefs not being saved correctly
	def fix_ckeditor_attachment_paths
	  if self.contents.include?("_cke_saved_href")
	  	self.contents.gsub!(/href=\"javascript:void\(0\)\/\*\d+\*\/\"/, '')
	  	self.contents.gsub!(/_cke_saved_href/, 'href')
	  end
	end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  
  layout "admin"
  
  before_filter do 
  	authenticate_user!
  	authenticate_cms_admin
  end
  
  # GET /docs
  # GET /docs.json
  def index
    if params[:view] == "last"
    	@docs = Doc.find_all_by_created_by(current_user.email)
    	unless @docs.blank?
    		@docs = [@docs.sort{|x,y| x.updated_at <=> y.updated_at}.last]
    	end
    elsif params[:view] == "deprecated"
    	@docs = Doc.find_all_by_deprecated(true)
    else
    	params[:search] ? @docs = Doc.search(params[:search]) : @docs = Doc.all
    end
    @latest_docs = Doc.get_latest_components

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @docs }
    end
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
    @doc = Doc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doc }
    end
  end

  # GET /docs/new
  # GET /docs/new.json
  def new
  	if params[:id]
  		@old_doc = Doc.find(params[:id])
  		@doc = Doc.new({:component => @old_doc.component, :maj_version => (params[:version] == "major" ? @old_doc.maj_version + 1 : @old_doc.maj_version ), :min_version => (params[:version] == "minor" ? @old_doc.min_version + 1 : @old_doc.min_version), :dev_stage => @old_doc.dev_stage, :url => @old_doc.new_version_url(params[:version]), :contents => @old_doc.contents})
  	else
	    @doc = Doc.new
		end
		
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doc }
    end
  end

  # GET /docs/1/edit
  def edit
    @doc = Doc.find(params[:id])
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = Doc.new(params[:doc])

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, notice: "\"#{@doc.component}\" was successfully created." }
        format.json { render json: @doc, status: :created, location: @doc }
      else
        format.html { render action: "new" }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /docs/1
  # PUT /docs/1.json
  def update
    @doc = Doc.find(params[:id])
    # do a check to make sure the editor hasn't incremented the version without making a new doc first - if true then create new doc instead
    @version = params[:doc][:dev_stage] + " " + params[:doc][:maj_version] + "." + params[:doc][:min_version]
		unless @doc.get_version == @version
			@new_doc = Doc.new(params[:doc])
			# increment the url as necessary
			if @new_doc.maj_version > @doc.maj_version
				url_parts = @new_doc.url.split("-")
				url_parts[url_parts.size - 2] = @new_doc.maj_version
				url_parts[url_parts.size - 1] = @new_doc.min_version
				@new_doc.url = url_parts.join("-")
			elsif @new_doc.maj_version == @doc.maj_version && @new_doc.min_version > @doc.min_version
				url_parts = @new_doc.url.split("-")
				url_parts[url_parts.size - 1] = @new_doc.min_version
				@new_doc.url = url_parts.join("-")
			else
				# default case where possibly the editor has graduated the dev stage to something different, will completely rebuild url using create_url at save
				@new_doc.url = ""
			end
			@new_doc.save
			redirect_to @new_doc, alert: "You have incremented the version for this doc, so a new doc was created with the version \"#{@version}\" instead." and return
		end
		
    respond_to do |format|
      if @doc.update_attributes(params[:doc])
        format.html { redirect_to @doc, notice: "\"#{@doc.component}\" was successfully updated." }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy

    respond_to do |format|
      format.html { redirect_to docs_url }
      format.json { head :ok }
    end
  end
  
  def show_revisions
  	@doc = Doc.find(params[:id])
  	@revisions = @doc.versions
  	
  	respond_to do |format|
  	  format.html
  	  format.json { render json: @doc }
  	end
  end
  
  def revert_revision
  
  	@doc = Doc.find(params[:id])
  	@lock_version = @doc.lock_version
  	@doc.revert_to(params[:version].to_i)
  	@doc.lock_version = @lock_version
  	@doc.updated_by = current_user.email
  	@doc.save
  	
  	redirect_to show_doc_revisions_path, :notice => "Successfully reverted to revision ##{params[:version]}."
  
  end
  
  def diff_content
  
  	@doc = Doc.find(params[:id])
  	@revision = Doc.find(params[:id])
  	@revision.revert_to(params[:revision].to_i)
  	
  	@doc.component = Differ.diff_by_word(@doc.component, @revision.component).format_as(:html)
  	@doc.contents = Differ.diff_by_line(@doc.contents, @revision.contents).format_as(:html)
  	
  	respond_to do |format|
  		format.html { render :layout => "site" }
  	end
  end
  
  protected 
  
  def correct_stale_object_version
  
  	@doc.reload.attributes = params[:page].reject do |attrb, value|
    	attrb.to_sym == :lock_version
    end
  end
end

app/helpers/docs_helper.rb
module DocsHelper

	def support_docs_url(doc)
	
		return "/support/api/" + doc.url
	
	end

end

app/views/docs/_form.html.erb
<%= form_for(@doc) do |f| %>
  <% if @doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% @doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.hidden_field :lock_version %>
  <div class="field">
    <%= f.label :component, "Component (please do not use the word GenomeSpace in title)" %><br />
    <%= f.text_field :component %>
  </div>
  <div class="field">
    <%= f.label :url, "URL (you can leave this blank to auto-generate a url based on the component, dev stage and version)" %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :dev_stage, "Development Stage" %><br />
    <%= f.select(:dev_stage, options_for_select(["alpha","beta","prod"], @doc.dev_stage)) %>
  </div>
  <div class="field">
    <%= f.label :maj_version, "Major Version" %><br />
    <%= f.number_field :maj_version %>
  </div>
  <div class="field">
    <%= f.label :min_version, "Minor Version" %><br />
    <%= f.number_field :min_version %>
  </div>
  <div class="field">
    <%= f.label :deprecated, "Deprecated?" %><br />
    <%= f.select :deprecated, options_for_select([["Yes", 1],["No", 0]], @doc.deprecated? ? ["Yes", 1] : ["No", 0]) %>
  </div>
  <div class="field">
    <%= f.label :dev, "Version in Dev (setting this flag will only make this revision viewable to logged-in users.  All other users see the last live version)?" %><br />
    <%= f.select :dev, options_for_select([["Yes", 1],["No", 0]], @doc.dev? ? ["Yes", 1] : ["No", 0]) %>
  </div>
  <div class="field">
    <%= f.label :contents %><br />
    <%= f.cktext_area :contents %>
  </div>
    <%= f.hidden_field :updated_by, :value => current_user.email %>
    <%= f.hidden_field :created_by, :value => current_user.email %>
  
  <div class="actions">
    <%= f.submit nil, {:onclick => "confirmUpdate();"} %>
  </div>
<% end %>

<%= javascript_tag do %>
	
		window.onbeforeunload = function() {
			if (CKEDITOR.instances.doc_contents.checkDirty() && update == false ) {
				return "You have unsaved changes."
			};
		};

<% end %>

app/views/docs/diff_content.html.erb
<hr />
<h1><%= @doc.component.html_safe %> (version <%= @doc.get_version %>)</h1>
<%= @doc.deprecated? ? "<h2 style='color: red;'>THIS API HAS BEEN DEPRECATED</h2>".html_safe : nil %>
<%= @doc.dev? ? "<p style='color: red;'>This doc is a dev revision.</p>".html_safe : nil %>
<%= @doc.contents.html_safe %>

app/views/docs/edit.html.erb
<h1>Editing "<em><%= @doc.component %></em>"</h1>

<%= render 'form' %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>

app/views/docs/index.html.erb
<h1>GenomeSpace API Documentation</h1>
<table id="filter_search">
	<tr><td>
		<%= form_tag docs_path, {:method => "get"} do %>
			<%= label_tag :view, "Available Actions:" %>
			<%= select_tag :view, options_for_select([["Your Last Edited Doc", "last"],["Deprecated Docs", "deprecated"]]), { :include_blank => true, :onchange => 'this.form.submit()'} %>
			<% end %>
	</td><td>
	<%= render "/layouts/admin_search" %>
	</td>
</table>
<table id="pages">
	<thead>
  <tr>
    <th>Component</th>
    <th>Url</th>
    <th>Version</th>
    <th>Deprecated?</th>
    <th>Updated by</th>
    <th>Contents</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
	</thead>
	<tbody>
<% @docs.each do |doc| %>
  <tr>
    <td><%= doc.component %></td>
    <td><%= doc.url %></td>
    <td><%= doc.get_version %></td>
    <td><%= doc.deprecated? ? "Yes" : "No" %></td>
    <td><%= doc.versions.blank? ? doc.created_by : doc.versions.last.user_name %></td>
    <td><center><%= link_to image_tag("view.gif"), support_docs_url(doc) %></center></td>
    <td><%= doc.version == 1 ? "N/A" : link_to('Revisions', show_doc_revisions_path(doc)) %></td>
    <td><%= link_to 'Edit', edit_doc_path(doc) %></td>
    <td><%= link_to 'Destroy', doc, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

<%= javascript_tag do %>

	$(document).ready(function() {
	    oTable = $('#pages').dataTable({
	        "bJQueryUI": true,
	        "sPaginationType": "full_numbers",
	        "aaSorting": [[0, "asc"],[2, "desc"]]
	        
	    });
	} );

<% end %>

<br />
<table><tr><td>
<%= button_to 'New Doc', new_doc_path, {:method => "get"} %></td><td><strong>OR COPY (non-deprecated):</strong></td>
<td><div id="copy_doc">
	<%= form_tag copy_doc_path, { :method => "get" } do |f| %>
		<%= label_tag "Component:" %>
		<%= select_tag :id, options_from_collection_for_select(@latest_docs, :id, :component) %>
		<%= label_tag "New Major/Minor Version?" %>
		<%= select_tag :version, options_for_select(["major", "minor"]) %>
		<%= submit_tag "Copy Doc", :name => nil %>
	<% end %>
</div></td></tr></table>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= render 'form' %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<h3>View Live <%= link_to image_tag("view.gif"), support_docs_url(@doc) %></h3>
<p>
  <b>Component:</b>
  <%= @doc.component %>
</p>

<p>
  <b>Full Version:</b>
  <%= @doc.get_version %>
</p>

<p>
  <b>URL:</b>
  <%= @doc.url %>
</p>

<p>
  <b>Version in Dev:</b>
  <%= @doc.dev %>
</p>

<p>
  <b>Contents:</b>
  <%= @doc.contents.html_safe %>
</p>


<%= link_to 'Edit', edit_doc_path(@doc) %> |
<%= link_to 'Back', docs_path %>

app/views/docs/show_revisions.html.erb
<h1>Listing Revisions for "<em><%= @doc.component %>, (version <%= @doc.get_version %>)</em>"</h1>

<table id="pages">
	<thead>
	<tr>
		<th>Revision</th>
	  <th>Changes</th>
	  <th>Updated By</th>
	  <th>Revert</th>
	</tr>
	</thead>
	<tbody>
	<% @revisions.each do |rev| %>
	<tr>
		<td><%= rev.number %></td>
		<td>
			<% unless rev.changes.blank? || rev.changes.is_a?(String) %>
				<% rev.changes.each do |k,v| %>
					<% unless k == "delta" || k == "lock_version" || k =~ /content/ %>
						<% @diff = Differ.diff_by_line(v[1].to_s, v[0].to_s) %>
						<%= "<em><strong>#{k}:</strong></em>".html_safe %><br />
						<% @results = Hpricot(@diff.format_as(:html)) %>
						<% @results.search("[@class='differ']").each do |r| %>
							<%= r.to_html.html_safe %><br />
						<% end %>
					<% end %>
					<% if k =~ "content" %>
						<%= "<em><strong>#{k}:</strong></em> View Changes ".html_safe %><%= link_to image_tag("view.gif"), diff_doc_content_path(@doc, rev.number - 1), {:title => "View changes"} %><br />
					<% end %>
				<% end %>
			<% else %>
				N/A
			<% end %>
		</td>
		<td><%= rev.user_name %></td>
		<td><%= rev.number == @doc.version ? "Current" : link_to("Revert", revert_doc_revision_path(@doc.id, rev.number), confirm: "Are you sure you want to revert to revision ##{rev.number}?  This will create a new revision (##{@doc.version + 1}) with that content." ) %></td>
	</tr>
	<% end %>
	<!-- Hard coded link to version #1 since this doesn't exist discretely in the database -->
	<tr>
		<td>1</td>
		<td>N/A</td>
		<td><%= @doc.created_by %></td>
		<td><%= link_to "Revert", revert_doc_revision_path(@doc.id, 1), confirm: "Are you sure you want to revert to revision #1?  This will create a new revision (##{@doc.version + 1}) with that content." %></td>
	</tr>
	</tbody>
</table>

<%= javascript_tag do %>

	$(document).ready(function() {
	    oTable = $('#pages').dataTable({
	        "bJQueryUI": true,
	        "sPaginationType": "full_numbers",
	        "aaSorting": [[0, "desc"]]
	    });
	} );

<% end %>
<br />
<%= link_to "Back", docs_path %>