config/routes.rb
GenomespaceNew::Application.routes.draw do
 
	mount Ckeditor::Engine => "/ckeditor"
	resources :server_properties
	match "sites/genomespacefiles/config/serverurl.properties" => "site#server_properties", :as => "view_server_properties"
	match "system-status/urgent(.format)" => "site#view_urgent_system_messages", :as => "view_urgent_system_messages"
	match "system-status/latest(.format)" => "site#view_system_message"
	match "system-status/:url" => "site#view_system_message", :as => "view_system_message", :constraints => {:url => /.*/} 
	match "system-status" => "site#view_system_messages", :as => "view_system_messages", :constraints => {:url => /.*/} 
  resources :system_messages

	post "slideshow_items/reorder_slideshow_items" => "slideshow_items#reorder_slideshow_items"
  resources :slideshow_items
  get "request_invite" => "site#request_invite", :as => "request_invite"
  post "request_invite" => "site#process_invite", :as => "process_invite"
  get "request_received" => "site#request_received", :as => "request_received"
  match "invites/send_registration_invite/:id" => "invites#send_registration_invite", :as => "send_registration_invite"
  post "invites/bulk_invites" => "invites#bulk_invites", :as => "bulk_invites"
  resources :invites

  match "pages/:id/show_revisions" => "pages#show_revisions", :as => "show_revisions"
	match "pages/:id/revert_revision/:version" => "pages#revert_revision", :as => "revert_revision"
  match "pages/diff_content/:id/revision/:revision" => "pages#diff_content", :as => "diff_page_content"
  resources :pages
  
  get "menu_items" => "menu_items#index", :as => "menu_items"
  post "reorder_menu_items/:category" => "menu_items#reorder_menu_items"
  
  resources :deliverables
  resources :tools
  
  match "guides/:guide_id/guide_sections/:id/show_revisions" => "guide_sections#show_revisions", :as => "show_guide_section_revisions"
  match "guides/:guide_id/guide_sections/:id/revert_revision/:version" => "guide_sections#revert_revision", :as => "revert_guide_section_revisions"
  match "guides/:guide_id/guide_sections/diff_content/:id/revision/:revision" => "guide_sections#diff_content", :as => "diff_guide_section_content"
  resources :guides do
  	resources :guide_sections
 		post "reorder_guide_sections" => "guide_sections#reorder_guide_sections"
 		post "nest_guide_section/:id" => "guide_sections#nest_guide_section"
 		post "denest_guide_section/:id" => "guide_sections#denest_guide_section"
  end
  
  match "docs/:id/show_revisions" => "docs#show_revisions", :as => "show_doc_revisions"
  match "docs/:id/revert_revision/:version" => "docs#revert_revision", :as => "revert_doc_revision"
  resources :docs
  match "docs/new/copy" => "docs#new", :as => "copy_doc"
  match "docs/diff_content/:id/revision/:revision" => "docs#diff_content", :as => "diff_doc_content"
	
	match "blog/report_abuse/:id" => "site#report_abuse", :as => "report_abuse"
	get "blog(/:url)" => "site#view_blog", :as => "view_blog", :constraints => {:url => /.*/} 
	match "latest_news" => "site#latest_news", :as => "latest_news"
	resources :posts
	
	resources :highlights
	match "news(/:url)" => "site#view_highlights", :as => "view_highlights"
	
  devise_for :users
  resources :users
    
  match "replace_selected_item/:id" => "site#replace_selected_item", :as => "replace_selected_item" 
  match "get_other_slideshow_items/:offset" => "site#get_other_slideshow_items", :as => "get_other_slideshow_items"
  match "team" => "site#team", :as => "team"
  match "team/deliverables" => "site#deliverables", :as => "view_deliverables"
  get "team/deliverables_report/:quarter" => "site#deliverables_report", :as => "view_deliverables_report"
  post "team/deliverables_report/:quarter" => "site#process_deliverables_report", :as => "process_deliverables_report"
  get "register" => "site#register", :as => "register_account"
  post "register" => "site#process_registration", :as => "process_registration"
  get "support" => "site#support", :as => "support"
  post "support" => "site#genomespace_google_groups", :as => "support_google_groups"
 	post "support/api/:url" => "site#view_docs"
 	match "support/api/:url(?:rev=:version)" => "site#view_docs"
 	match "support/guides/:url/print" => "site#print_guide", :as => "print_guide"
 	match "recipes" => redirect("/support/guides/recipes")
 	match "support/guides/:url" => "site#view_guide"
 	match "support/guides/:url/sections/:display_url(?:rev=:version)" => "site#view_guide"
 	match "support/guides/:url/sections/:display_url/instructions" => "site#recipe_instructions"
 	match "support/tools(/:lookup_name)" => "site#tools", :as => "view_tools"
 	match "search" => "site#search", :as => "search"
 	match "search/google/:search" => "site#google_search", :as => "google_search"
 	post "route_action" => "application#route_action", :as => "route_action"
  match "admin" => "application#admin", :as => "admin"
  match "/:url(?:rev=:version)" => "site#view" 
  get "/" => "site#index", :as => "site"
  root :to => "site#index"
  match "*a" => "site#rescue_from_nil_page", :constraints => lambda{|req| req.env["REQUEST_PATH"] !~ /(ckeditor|assets)/ }

end

app/controllers/guide_sections_controller.rb
class GuideSectionsController < ApplicationController

	layout "admin"
	
	before_filter do 
		authenticate_user!
		authenticate_cms_admin
	end

  # GET /guide_sections
  # GET /guide_sections.json
  def index
  	@guide = Guide.find(params[:guide_id])
    @guide_sections = GuideSection.find_all_by_guide_id(params[:guide_id], :order => "display_order ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guide_sections }
    end
  end

  # GET /guide_sections/1
  # GET /guide_sections/1.json
  def show
  	@guide = Guide.find(params[:guide_id])
    @guide_section = GuideSection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guide_section }
    end
  end

  # GET /guide_sections/new
  # GET /guide_sections/new.json
  def new
  	@guide = Guide.find(params[:guide_id])
    @guide_section = @guide.guide_sections.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guide_section }
    end
  end

  # GET /guide_sections/1/edit
  def edit
  	@guide = Guide.find(params[:guide_id])
    @guide_section = GuideSection.find(params[:id])
  end

  # POST /guide_sections
  # POST /guide_sections.json
  def create
  	@guide = Guide.find(params[:guide_id])
    @guide_section = GuideSection.new(params[:guide_section])

    respond_to do |format|
      if @guide_section.save
        format.html { redirect_to [@guide, @guide_section], notice: "\"#{@guide_section.title}\" was successfully created." }
        format.json { render json: [@guide, @guide_section], status: :created, location: [@guide, @guide_section] }
      else
        format.html { render action: "new" }
        format.json { render json: [@guide, @guide_section].errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guide_sections/1
  # PUT /guide_sections/1.json
  def update
  	@special_alert = nil
  	@guide = Guide.find(params[:guide_id])
    @guide_section = GuideSection.find(params[:id])
    if @guide_section.has_children? && params[:guide_section][:published] == "0"
			params[:guide_section][:published] = "1"
			@special_alert = "Guide Sections with child sections cannot be unpublished.  Please move any child sections to other parts of this guide if you wish to unpublish this guide section."
		end
    respond_to do |format|
      if @guide_section.update_attributes(params[:guide_section])
        format.html { redirect_to [@guide, @guide_section], notice: "\"#{@guide_section.title}\" section was successfully updated.", alert: @special_alert}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: [@guide, @guide_section].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guide_sections/1
  # DELETE /guide_sections/1.json
  def destroy
    @guide_section = GuideSection.find(params[:id])
    # save display order and parent id for use later in reordering sections
    @display_order = @guide_section.display_order
    @parent_id = @guide_section.parent_id
    @destroyed = @guide_section.id
    @guide_section.destroy
    
    @guide = Guide.find(params[:guide_id])
    @guide_sections = GuideSection.find_all_by_guide_id(@guide.id, :order => "display_order ASC")
    # reorder sections so that there are no gaps unless the section just deleted was the last
    unless @display_order == @guide_sections.size
    	counter = 1
	    @guide_sections.each do |guide_section|
	    	guide_section.display_order = counter
	    	# if destroy section had children then denest all children one level
	    	guide_section.parent_id == @destroyed ? guide_section.parent_id = @parent_id : nil
	    	guide_section.save
	    	counter += 1
	    end
	  end

    respond_to do |format|
      format.html { redirect_to guide_guide_sections_url }
      format.json { head :ok }
    end
  end
  
  def show_revisions
  	@guide = Guide.find(params[:guide_id])
  	@guide_section = GuideSection.find(params[:id])
  	@revisions = @guide_section.versions
  	
  	respond_to do |format|
  	  format.html
  	  format.json { render json: [@guide, @guide_section] }
  	end
  
  end
  
  def revert_revision
  	@guide = Guide.find(params[:guide_id])
  	@guide_section = GuideSection.find(params[:id])
  	@lock_version = @guide_section.lock_version
  	@guide_section.revert_to(params[:version].to_i)
  	@guide_section.lock_version = @lock_version
  	@guide_section.updated_by = current_user.email
  	@guide_section.save
  	
  	redirect_to show_guide_section_revisions_path, notice: "Successfully reverted to revision ##{params[:version]}."
  
  end
  
  def diff_content
  
  	@guide = Guide.find(params[:guide_id])
  	@guide_section = GuideSection.find(params[:id])
  	@revision = GuideSection.find(params[:id])
  	@revision.revert_to(params[:revision].to_i)
  	
  	@guide_section.title = Differ.diff_by_word(@guide_section.title, @revision.title).format_as(:html)
  	@guide_section.content = Differ.diff_by_line(@guide_section.content, @revision.content).format_as(:html)
  	
  	respond_to do |format|
  		format.html { render :layout => "site" }
  	end
  
  end
  
  # reorders guide sections based on post from table.  gets an array of ids that is looped through to set order based on a counter (i).
  def reorder_guide_sections
  
  	@guide = Guide.find(params[:guide_id])
  	@new_order = params[:guide_section].collect {|n| n.to_i}
  	@sanitized_order = []
		@sanity_check = true
		while @new_order.first != nil && @sanity_check == true
			guide_section = GuideSection.find(@new_order.first)
			if !guide_section.parent_id.nil?
				@sanity_check = false
			elsif guide_section.has_children?
				@sanitized_order << @new_order.first
				@new_order.delete(@new_order.first)
				next_section = GuideSection.find(@new_order.first)
				children = guide_section.get_children
				# looks to see if the next section is at the root level, if so it moves children & sub children up en masse
				if next_section.parent_id.nil?
					children.each do |child|
						@sanitized_order << child.id
						@new_order.delete(child.id)
						if child.has_children?
							sub_children = child.get_children
							sub_children.each do |sub_child|
								@sanitized_order << sub_child.id
								@new_order.delete(sub_child.id)
							end
						end
					end
				# if the next section has the same parent id but is not in the right order, adjust as necessary
				elsif next_section.parent_id == guide_section.id 
					child_ids = children.collect(&:id)
					child_order = @new_order & child_ids
					child_order.each do |c|
						child = GuideSection.find(c)
						@sanitized_order << c
						@new_order.delete(c)
						if child.has_children?
							sub_children = child.get_children
							sub_child_ids = sub_children.collect(&:id)
							sub_child_order = @new_order & sub_child_ids
							sub_child_order.each do |sc|
								@sanitized_order << sc
								@new_order.delete(sc)
							end
						end
					end
				else
					@sanity_check = false
				end
			else # root level, no children
				@sanitized_order << @new_order.first
				@new_order.delete(@new_order.first)
			end
		end
		
		unless @sanity_check == false
			i = 1
			@sanitized_order.each do |new|
				guide_section = GuideSection.find(new)
				guide_section.display_order = i
				guide_section.save
				i += 1
			end
  	else
  		@flash_alert = "The specified order is invalid.  Please try again."
  	end
  	
  	@guide_sections = GuideSection.find_all_by_guide_id(@guide.id, :order => "display_order ASC")  
  	
  	respond_to do |format|
  	  format.js
  	end
  end
  
  # sets parent_id of given guide_section to be the item before.  has checks to preserve correct nesting.
  def nest_guide_section
  
  	@guide = Guide.find(params[:guide_id])
  	@guide_section = GuideSection.find(params[:id])
		@before_section = GuideSection.find_by_display_order_and_guide_id(@guide_section.display_order - 1, @guide.id)
		unless @before_section.parent_id.nil?
			@before_section_parent = GuideSection.find(@before_section.parent_id)
		end
		# items are at the same level
		if @before_section.parent_id.nil? || @before_section.parent_id == @guide_section.parent_id
			@guide_section.parent_id = @before_section.id
		# item is at root and before_section is at 2nd level, get super parent id
		elsif !@before_section_parent.nil? && !@before_section_parent.parent_id.nil? && @guide_section.parent_id.nil?
			@guide_section.parent_id = @before_section_parent.parent_id
		# item is 1 level below 
		else
			@guide_section.parent_id = @before_section.parent_id
		end
		@guide_section.save
		
		@guide_sections = GuideSection.find_all_by_guide_id(@guide.id, :order => "display_order ASC")  
		
		respond_to do |format|
		  format.js
		end
  end
  
  # removes appropriate parent_id from given guide_section and resets accordingly.
  def denest_guide_section
  
  	@guide = Guide.find(params[:guide_id])
  	@guide_section = GuideSection.find(params[:id])
		@before_section = GuideSection.find_by_guide_id_and_display_order(@guide.id, @guide_section.display_order - 1)
		@after_section = GuideSection.find_by_guide_id_and_display_order(@guide.id, @guide_section.display_order + 1)
		# checks if guide_section is the first child of a sub_section; important for reordering all other child sections later
		if @guide_section.first_child?
			@was_first_child = true
			@previous_parent_id = @guide_section.parent_id
		end
		unless @before_section.parent_id.nil?
			@before_section_parent = GuideSection.find(@before_section.parent_id)
		end
		# item before WAS the parent, now nesting under the before item's parent
		if @guide_section.parent_id == @before_section.id
			@guide_section.parent_id = @before_section.parent_id
		# items were both nested at same level, need to get super parent id (which may be nil)
		elsif @guide_section.parent_id == @before_section.parent_id
			@guide_section.parent_id = @before_section_parent.parent_id

app/helpers/guide_sections_helper.rb
module GuideSectionsHelper

	def toc_url(guide, guide_section)
		return "/support/guides/" + guide.url + "/sections/" + guide_section.display_url
	end
	
	def next_guide_section_url(guide, guide_sections, requested_section)
		return "/support/guides/#{guide.url}/sections/#{guide_sections[guide_sections.index(requested_section) + 1].display_url}"
	end
	
	def previous_guide_section_url(guide, guide_sections, requested_section)
		return "/support/guides/#{guide.url}/sections/#{guide_sections[guide_sections.index(requested_section) - 1].display_url}"
	end

end

app/views/guide_sections/_form.html.erb
<%= form_for([@guide, @guide_section]) do |f| %>
  <% if @guide_section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide_section.errors.count, "error") %> prohibited this guide_section from being saved:</h2>

      <ul>
      <% @guide_section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :guide_id, :value => params[:guide_id] %>
  <%= f.hidden_field :lock_version %>
	<div class="field">
	  <%= f.label :title %><br />
	  <%= f.text_field :title %>
	</div>
	<div class="field">
	  <%= f.label :display_url, "Display URL (you can leave this blank to auto-generate a url based on the guide section title)" %><br />
	  <%= f.text_field :display_url %>
	</div>
	<div class="field">
	  <%= f.label :display_order, "Display Order (this is only editable from the index view)" %><br />
	  <%= f.text_field :display_order, :readonly => true, :value => @guide_section.display_order.nil? ? GuideSection.get_next_display_order(params[:guide_id]) : @guide_section.display_order %>
	</div>
	<div class="field">
	  <%= f.label :dev, "Version in Dev (setting this flag will only make this revision viewable to logged-in users.  All other users see the last live version)?" %><br />
	  <%= f.select :dev, options_for_select([["Yes", 1],["No", 0]], @guide_section.dev? ? ["Yes", 1] : ["No", 0]) %>
	</div>
	<div class="field">
	  <%= f.label :published, "Published? (unpublished guide sections will not appear publicly in the guide and require authentication to view)" %><br />
	  <%= f.select :published, options_for_select([["Yes", 1],["No", 0]], @guide_section.published? ? ["Yes", 1] : ["No", 0]) %>
	</div>
	<div class="field">
	  <%= f.label :content %><br />
	  <%= f.cktext_area :content %>
	</div>
	<%= f.hidden_field :created_by, :value => current_user.email %>
	<%= f.hidden_field :updated_by, :value => current_user.email %>
  <div class="actions">
    <%= f.submit nil, {:onclick => "confirmUpdate();"} %>
  </div>
<% end %>
<%= javascript_tag do %>
	
		window.onbeforeunload = function() {
			if (CKEDITOR.instances.guide_section_content.checkDirty() && update == false ) {
				return "You have unsaved changes."
			};
		};
		
		$("#guide_section_title").change(function() {
			var title = getTextForUrl("guide_section_title");
			$("#guide_section_display_url").val(title);
		});

<% end %>

app/views/guide_sections/_guide_sections_table.html.erb
<p id="alert"><%= @flash_alert %></p>
<table id="guide_sections_table">
<thead>
  <tr>
    <th>Display Order</th>
    <th>Title</th>
    <th>Nest Under?</th>
    <th>Display URL</th>
    <th>Version in Dev?</th>
    <th>Published?</th>
    <th>Updated by</th>
    <th>Last Updated</th>
    <th>Date Created</th>
    <th>Preview</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody id="guide_sections_list" class="sortable">
<% @guide_sections.each do |guide_section| %>
  <%= "<tr id=\"guide_section_#{guide_section.id}\">".html_safe %>
  	<td width="10%"><center><%= guide_section.check_denesting? ? link_to_function(image_tag("denest_on.png"), "deNestGuideSection('#{guide_section.id}')".html_safe, :class => "denest_guide_section") : image_tag("denest_off.png") %><%= guide_section.display_order %><%= guide_section.check_nesting? ? link_to_function(image_tag("nest_on.png"), "nestGuideSection('#{guide_section.id}')".html_safe, :class => "nest_guide_section") : image_tag("nest_off.png") %></center></td>
  	<td><%= guide_section.get_nesting_display.html_safe %> <%= guide_section.title %></td>
  	<td><%= guide_section.parent_id.nil? ? "N/A" : truncate(GuideSection.find(guide_section.parent_id).title, :length => 25)%></td>
  	<td><%= guide_section.display_url %></td>
  	<td><%= guide_section.dev? ? "Yes" : "No" %></td>
  	<td><%= guide_section.published? ? "Yes" : "No" %></td>
  	<td><%= guide_section.versions.blank? ? guide_section.created_by : guide_section.versions.last.user_name %></td>
  	<td><%= guide_section.updated_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
  	<td><%= guide_section.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
    <td><center><%= link_to image_tag("view.gif"), toc_url(@guide, guide_section) %></center></td>
    <td><%= guide_section.version == 1 ? "N/A" : link_to('Revisions', show_guide_section_revisions_path(@guide, guide_section)) %></td>
    <td><%= link_to 'Edit', edit_guide_guide_section_path(@guide, guide_section) %></td>
    <td><%= link_to 'Destroy', guide_guide_section_path(@guide, guide_section), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

<%= javascript_tag do %>

	$(function() { 
	  $("#guide_sections_table tbody.sortable").sortable({
	  	update: function() {
	  		$.ajax({
	  			type: 'POST',
	  			url: "reorder_guide_sections",
	  			data: $("#guide_sections_table tbody.sortable").sortable('serialize')
	  		});
	  	}
	  }); 
	});
	
	function nestGuideSection( guide_section_id ) {
		$.ajax({
			type: 'POST',
			url: "nest_guide_section/" + guide_section_id
		});
	};
	
	function deNestGuideSection( guide_section_id ) {
		$.ajax({
			type: 'POST',
			url: "denest_guide_section/" + guide_section_id
		});
	};
	
	$(document).ready(function() {
	    oTable = $('#guide_sections_table').dataTable({
	        "bJQueryUI": true,
	        "bSort": false,
	        "iDisplayLength": 100,
	        "bFilter": false,
	        "bLengthChange": false,
	        "bPaginate": false,
	    });
	} );
<% end %>

app/views/guide_sections/denest_guide_section.js.erb
$("#guide_sections_target").html("<%= escape_javascript(render(:partial => 'guide_sections_table')) %>");

app/views/guide_sections/diff_content.html.erb
<h1><%= @guide_section.title %></h1>
<%= @guide_section.dev? ? "<p style='color: red;'>This section is a dev revision.</p>".html_safe : nil %>
<%= @guide_section.content.html_safe %>

app/views/guide_sections/edit.html.erb
<h1>Editing "<em><%= @guide_section.title %></em>"</h1>

<%= render 'form' %>

<%= link_to 'Show', guide_guide_section_path(@guide, @guide_section) %> |
<%= link_to 'Back', guide_guide_sections_path %>

app/views/guide_sections/index.html.erb
<h1>Listing All Sections for "<em><%= @guide.title %></em>"</h1>

<div id="guide_sections_target">
	<%= render "guide_sections_table" %>
</div>
<p>Click and drag on any table row to reorder the sections.  To nest/denest a section, click the arrows next to the display order number for that section.  Moving a section with nested child sections will move the entire group en masse.</p>

<%= button_to 'New Guide section', new_guide_guide_section_path, { :method => "get" } %>
<p><%= link_to "Back", guides_path %></p>

app/views/guide_sections/nest_guide_section.js.erb
$("#guide_sections_target").html("<%= escape_javascript(render(:partial => 'guide_sections_table')) %>");

app/views/guide_sections/new.html.erb
<h1>New Section for "<em><%= @guide.title %></em>"</h1>

<%= render 'form' %>

<%= link_to 'Back', guide_guide_sections_path %>

app/views/guide_sections/reorder_guide_sections.js.erb
$("#guide_sections_target").html("<%= escape_javascript(render(:partial => 'guide_sections_table')) %>");

app/views/guide_sections/show.html.erb
<h3>View Live <%= link_to image_tag("view.gif"), toc_url(@guide, @guide_section) %></h3>
<p>
  <b>Title:</b>
  <%= @guide_section.title %>
</p>

<p>
  <b>Display URL:</b>
  <%= @guide_section.display_url %>
</p>

<p>
  <b>Display Order:</b>
  <%= @guide_section.display_order %>
</p>

<p>
  <b>Version in Dev:</b>
  <%= @guide_section.dev %>
</p>

<p>
  <b>Published</b>
  <%= @guide_section.published %>
</p>

<p>
  <b>Content:</b></p>
  <%= @guide_section.content.html_safe %>
</p>

<%= link_to 'Edit', edit_guide_guide_section_path(@guide, @guide_section) %> |
<%= link_to 'Back', guide_guide_sections_path %>

app/views/guide_sections/show_revisions.html.erb
<h1>Listing Revisions for "<em><%= @guide_section.title %></em>"</h1>

<table id="pages">
	<thead>
	<tr>
		<th>Revision</th>
	  <th>Changes</th>
	  <th>Updated By</th>
	  <th>Revert</th>
	</tr>
	</thead>
	<tbody>
	<% @revisions.each do |rev| %>
	<tr>
		<td><%= rev.number %></td>
		<td>
			<% unless rev.changes.blank? || rev.changes.is_a?(String) %>
				<% rev.changes.each do |k,v| %>
					<% unless k == "delta" || k == "lock_version" || k =~ /content/ %>
						<% @diff = Differ.diff_by_line(v[1].to_s, v[0].to_s) %>
						<%= "<em><strong>#{k}:</strong></em>".html_safe %><br />
						<% @results = Hpricot(@diff.format_as(:html)) %>
						<% @results.search("[@class='differ']").each do |r| %>
							<%= r.to_html.html_safe %><br />
						<% end %>
					<% end %>
					<% if k =~ /content/ %>
						<%= "<em><strong>#{k}:</strong></em> View Changes ".html_safe %><%= link_to image_tag("view.gif"), diff_guide_section_content_path(@guide, @guide_section, rev.number - 1), {:title => "View changes"} %><br />
					<% end %>
				<% end %>
			<% else %>
				N/A
			<% end %>
		</td>
		<td><%= rev.user_name %></td>
		<td><%= rev.number == @guide_section.version ? "Current" : link_to("Revert", revert_guide_section_revisions_path(@guide.id, @guide_section.id, rev.number), confirm: "Are you sure you want to revert to revision ##{rev.number}?  This will create a new revision (##{@guide_section.version + 1}) with that content." ) %></td>
	</tr>
	<% end %>
	<!-- Hard coded link to version #1 since this doesn't exist discretely in the database -->
	<tr>
		<td>1</td>
		<td>N/A</td>
		<td>N/A</td>
		<td><%= link_to "Revert", revert_guide_section_revisions_path(@guide.id, @guide_section.id, 1), confirm: "Are you sure you want to revert to revision #1?  This will create a new revision (##{@guide_section.version + 1}) with that content."  %></td>
	</tr>
	</tbody>
</table>

<%= javascript_tag do %>

	$(document).ready(function() {
	    oTable = $('#pages').dataTable({
	        "bJQueryUI": true,
	        "sPaginationType": "full_numbers",
	        "aaSorting": [[0, "desc"]]
	    });
	} );

<% end %>
<br />
<%= link_to "Back", guide_guide_sections_path %>