config/routes.rb
GenomespaceNew::Application.routes.draw do
 
	mount Ckeditor::Engine => "/ckeditor"
	resources :server_properties
	match "sites/genomespacefiles/config/serverurl.properties" => "site#server_properties", :as => "view_server_properties"
	match "system-status/urgent(.format)" => "site#view_urgent_system_messages", :as => "view_urgent_system_messages"
	match "system-status/latest(.format)" => "site#view_system_message"
	match "system-status/:url" => "site#view_system_message", :as => "view_system_message", :constraints => {:url => /.*/} 
	match "system-status" => "site#view_system_messages", :as => "view_system_messages", :constraints => {:url => /.*/} 
  resources :system_messages

	post "slideshow_items/reorder_slideshow_items" => "slideshow_items#reorder_slideshow_items"
  resources :slideshow_items
  get "request_invite" => "site#request_invite", :as => "request_invite"
  post "request_invite" => "site#process_invite", :as => "process_invite"
  get "request_received" => "site#request_received", :as => "request_received"
  match "invites/send_registration_invite/:id" => "invites#send_registration_invite", :as => "send_registration_invite"
  post "invites/bulk_invites" => "invites#bulk_invites", :as => "bulk_invites"
  resources :invites

  match "pages/:id/show_revisions" => "pages#show_revisions", :as => "show_revisions"
	match "pages/:id/revert_revision/:version" => "pages#revert_revision", :as => "revert_revision"
  match "pages/diff_content/:id/revision/:revision" => "pages#diff_content", :as => "diff_page_content"
  resources :pages
  
  get "menu_items" => "menu_items#index", :as => "menu_items"
  post "reorder_menu_items/:category" => "menu_items#reorder_menu_items"
  
  resources :deliverables
  resources :tools
  
  match "guides/:guide_id/guide_sections/:id/show_revisions" => "guide_sections#show_revisions", :as => "show_guide_section_revisions"
  match "guides/:guide_id/guide_sections/:id/revert_revision/:version" => "guide_sections#revert_revision", :as => "revert_guide_section_revisions"
  match "guides/:guide_id/guide_sections/diff_content/:id/revision/:revision" => "guide_sections#diff_content", :as => "diff_guide_section_content"
  resources :guides do
  	resources :guide_sections
 		post "reorder_guide_sections" => "guide_sections#reorder_guide_sections"
 		post "nest_guide_section/:id" => "guide_sections#nest_guide_section"
 		post "denest_guide_section/:id" => "guide_sections#denest_guide_section"
  end
  
  match "docs/:id/show_revisions" => "docs#show_revisions", :as => "show_doc_revisions"
  match "docs/:id/revert_revision/:version" => "docs#revert_revision", :as => "revert_doc_revision"
  resources :docs
  match "docs/new/copy" => "docs#new", :as => "copy_doc"
  match "docs/diff_content/:id/revision/:revision" => "docs#diff_content", :as => "diff_doc_content"
	
	match "blog/report_abuse/:id" => "site#report_abuse", :as => "report_abuse"
	get "blog(/:url)" => "site#view_blog", :as => "view_blog", :constraints => {:url => /.*/} 
	match "latest_news" => "site#latest_news", :as => "latest_news"
	resources :posts
	
	resources :highlights
	match "news(/:url)" => "site#view_highlights", :as => "view_highlights"
	
  devise_for :users
  resources :users
    
  match "replace_selected_item/:id" => "site#replace_selected_item", :as => "replace_selected_item" 
  match "get_other_slideshow_items/:offset" => "site#get_other_slideshow_items", :as => "get_other_slideshow_items"
  match "team" => "site#team", :as => "team"
  match "team/deliverables" => "site#deliverables", :as => "view_deliverables"
  get "team/deliverables_report/:quarter" => "site#deliverables_report", :as => "view_deliverables_report"
  post "team/deliverables_report/:quarter" => "site#process_deliverables_report", :as => "process_deliverables_report"
  get "register" => "site#register", :as => "register_account"
  post "register" => "site#process_registration", :as => "process_registration"
  get "support" => "site#support", :as => "support"
  post "support" => "site#genomespace_google_groups", :as => "support_google_groups"
 	post "support/api/:url" => "site#view_docs"
 	match "support/api/:url(?:rev=:version)" => "site#view_docs"
 	match "support/guides/:url/print" => "site#print_guide", :as => "print_guide"
 	match "recipes" => redirect("/support/guides/recipes")
 	match "support/guides/:url" => "site#view_guide"
 	match "support/guides/:url/sections/:display_url(?:rev=:version)" => "site#view_guide"
 	match "support/guides/:url/sections/:display_url/instructions" => "site#recipe_instructions"
 	match "support/tools(/:lookup_name)" => "site#tools", :as => "view_tools"
 	match "search" => "site#search", :as => "search"
 	match "search/google/:search" => "site#google_search", :as => "google_search"
 	post "route_action" => "application#route_action", :as => "route_action"
  match "admin" => "application#admin", :as => "admin"
  match "/:url(?:rev=:version)" => "site#view" 
  get "/" => "site#index", :as => "site"
  root :to => "site#index"
  match "*a" => "site#rescue_from_nil_page", :constraints => lambda{|req| req.env["REQUEST_PATH"] !~ /(ckeditor|assets)/ }

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	before_filter :authenticate_user!, :only => ["team", "deliverables", "deliverables_report"]
	after_filter :cors_set_access_control_headers

  def index

		#@page, @alert = Page.get_home_page.check_version(params, user_signed_in?)
		#unless @alert.nil? then flash.now[:alert] = @alert.html_safe end # will have message from Page.check_version if user was not logged in

		#if @page.dev?
		#	@page = @page.get_last_live
		#end

		@highlights = Highlight.where(:dev => false).order("created_at DESC").limit(2)
		@posts = Post.where(:published => true).order("created_at DESC").limit(2)
		# @slideshow_items = SlideshowItem.order("display_order ASC").limit(6)
		# @selected_item = @slideshow_items.first
		@system_message = SystemMessage.all_valid_messages.first
		@control_offset = 6

		#@yt_feed = JSON.parse(RestClient.get "http://gdata.youtube.com/feeds/api/users/broadcancerdev/uploads/-/GenomeSpace?v=2&max-results=8&alt=json")
		#@available_videos = @yt_feed["feed"]["entry"]

  	respond_to do |format|
  		format.html { render :layout => "site_index" }
  	end
  end

  def replace_selected_item
  	params[:id].nil? ? @selected_item = SlideshowItem.first : @selected_item = SlideshowItem.find(params[:id])

  	respond_to do |format|
  		format.js
  	end
  end

  def get_other_slideshow_items
  	offset = params[:offset].to_i
  	@control_offset = offset + 6
  	@slideshow_items = SlideshowItem.order("display_order ASC").limit(6).offset(offset)

  	respond_to do |format|
  		format.js
  	end
  end

  def view
	  @page = Page.find_by_url(params[:url])

  	# clause to catch a user requesting a page by a url that isn't live anymore
  	unless @page.nil?
  		@page, @alert = @page.check_version(params, user_signed_in?)
  		# gotcha for navigating to the home page by its discrete url
  		if @page.home_page? then redirect_to :action => "index" and return end
  		unless @alert.nil? then flash.now[:alert] = @alert.html_safe end
  	else
  		redirect_to(request.referrer.nil? ? site_path : request.referrer, :alert => "The url you requested: \"#{request.fullpath}\" does not currently exist.  Please check again before continuing.") and return
  	end

  	# check if the page is currently published or is a team page
  	if (!@page.published? || @page.team_page?) && !user_signed_in?
  		redirect_to(request.referrer.nil? ? site_path : request.referrer, :alert => "You must be <a href='/users/sign_in'>logged in</a> to view: \"#{request.fullpath}.\"".html_safe) and return
  	elsif !@page.published? && user_signed_in?
  		flash.now[:alert] = "This page is currently not published."
  	end

  	if @page.dev? && @page.version > 1 && !user_signed_in?
  		@page = @page.get_last_live
  	elsif @page.dev? && @page.version == 1 && !user_signed_in?
  		redirect_to(request.referrer.nil? ? site_path : request.referrer, :alert => "You must be <a href='/users/sign_in'>logged in</a> to view: \"#{request.fullpath}.\"".html_safe) and return
  	end

  	respond_to do |format|
  		format.html
  		format.json {render json: @page}
  	end
  end

  def team

  	@team_pages = Page.find_all_by_team_page(true, :order => "title ASC")

  	respond_to do |format|
  		format.html
  	end

  end
  # return a list of all deliverables
  def deliverables

  	# construct a hash of all deliverables keyed by quarter
  	@deliverables = Hash.new
  	(1..16).each do |i|
  		quarter = "Q#{i}"
  		@deliverables[quarter] = Deliverable.find_all_by_quarter(quarter, :order => "identifier ASC")
  	end

  	# construct a hash of all artifacts keyed by deliverable.id
  	@artifacts = Hash.new
  	@deliverables.each do |quarter,deliverable|
  		deliverable.each do |d|
	  		@artifacts[d.id] = Artifact.find_by_deliverable_id(d.id)
	  	end
  	end

  	respond_to do |format|
  		format.html
  	end

  end

  def deliverables_report

  	@quarter = params[:quarter]

  	# find all non-technical deliverables for the given quarter
  	@deliverables = Deliverable.find_all_by_quarter_and_tech(@quarter, false, :order => "identifier ASC")
  	@deliverable_ids = []
  	@artifacts = Hash.new
  	@deliverables.each do |d|
  		@artifacts[d.id] = Artifact.find_by_deliverable_id(d.id)
  		@deliverable_ids << d.id # for use in parsing approvals later
  	end

  	respond_to do |format|
  		format.html
  	end

  end

  def process_deliverables_report

  	@report = params[:report]
  	# grab array of deliverable ids to process
  	tmp = params[:report][:deliverable_ids][1..-2].split(',')
  	@ids = []
  	tmp.each {|t| @ids << t.strip.to_i }
  	# array to hold each deliverable for confirmation email sent to genomespace team
  	@deliverables = []
  	# process each approval
  	@ids.each do |i|
  		@deliverable = Deliverable.find(i)
  		@deliverable.completed = @report["deliverable_#{i}_completed"].to_i
  		@deliverable.approval_comments = @report["deliverable_#{i}_approval_comments"]
  		@deliverable.approved_by = @report["deliverable_#{i}_approved_by"]
  		@deliverable.save
  		@deliverables << @deliverable
  	end
  	@host = request.host_with_port
  	GenomespaceMailer.deliverables_report_email(@deliverables, @host).deliver
  	redirect_to request.referrer, notice: "Your approvals have been recorded."

  end

  def register
  	@username = params[:username]
  	@email = params[:email]

  	respond_to do |format|
  		format.html
  	end

  end

  # register for a genomespace account (note this is for genomespace as a service, not the genomespace website).
  def process_registration

  	@account = params[:account]
  	@host = request.env['HTTP_HOST']

  	# confirm passwords match
  	unless @account["password"] == @account["password_confirm"]
  		redirect_to(register_account_path(:username => @account["username"],:email => @account["email"]), :alert => "<h3 class='invite_alert'>Passwords do not match.  Please re-enter before continuing.</h3>".html_safe) and return
  	end

  	# make post to identity server and handle response (either 200 or 409)

  	RestClient.post("https://identity.genomespace.org/identityServer/usermanagement/register/initial", {'username' => @account["username"], 'email' => @account["email"], 'roles' => "public", 'password' => @account["password"]}.to_json, :content_type => :json) {|response, request, result, &block|

			case response.code
			when 200
		  	# server does not return any response

		  when 409
		  	# 409 is returned when the username already exists
		  	logger.error "Error: #{response.code}, #{response}"
		  	redirect_to(register_account_path(:username => @account["username"],:email => @account["email"]), :alert => "<h3 class='invite_alert'>An error has occured while processing your request: #{response}<br/>If you believe this has happened in error, you may <a href=\"https://gsui.genomespace.org/jsui/gsui.html\">log in</a> now or request a <a href=\"https://identity.genomespace.org:8444/identityServer/forgotPassword.html?openId.return_to='https://gsui.genomespace.org/jsui/openIdClient?is_cancel=true'\">new password</a>.</h3>".html_safe) and return
		  else
		  	# generic catch-all
		  	logger.error "Error: #{response.code}, #{response}"
		  	redirect_to(register_account_path, :alert => "An HTTP #{response.code} exception has been raised: <br />Response: #{response}".html_safe) and return
		  end
		}

  	respond_to do |format|
  		format.html
  	end
  end

  def request_invite

  	respond_to do |format|
  		format.html
  	end

  end

  def process_invite
  	if params[:invite][:email].blank? || (params[:invite][:email] =~ Devise.email_regexp).nil?
  		redirect_to request_invite_path, :alert => "You must enter a valid email address." and return
  	end
  	@invite = Invite.create(params[:invite])

  	redirect_to request_received_path
  end

  # display a list of all available docs, latest versions only
  def support

  	@docs = Doc.get_latest_components
  	@guides = Guide.all(:order => "title ASC")

  	respond_to do |format|
  		format.html
  		format.json {render json: [@docs, @guides]}
  	end

  end

  def genomespace_google_groups

  	unless params[:email].nil? || params[:email].blank?
	  	@lists = []
	  	params.each {|k,v| v == "1" ? @lists << k : nil}
	  	GenomespaceMailer.subscribe_email_list(params[:email], @lists).deliver
	  else
	  	redirect_to support_path, alert: "You must enter an email address to subscribe to a list." and return
		end

		respond_to do |format|
			format.html
		end
  end

  # displays current doc along with a dropdown to easily load other docs
  def view_docs

  	# if user has selected a component from the dropdown, then overwrite the url to the selected component to load correct doc
  	if params[:select]
  		params[:url] = params[:select][:component]
  	end

  	@doc = Doc.find_by_url(params[:url])
  	if @doc.nil?
  		@doc = Doc.get_latest_version(params[:url])
  	end
  	@doc, @alert = @doc.check_version(params, user_signed_in?)
  	unless @alert.nil? then flash.now[:alert] = @alert.html_safe end
  	if @doc.dev? && !user_signed_in?
  		@doc = @doc.get_last_live
  	elsif @doc.dev? && @doc.version == 1 && !user_signed_in?
  		redirect_to(request.referrer.nil? ? site_path : request.referrer, :alert => "You must be <a href='/users/sign_in'>logged in</a> to view: \"#{request.fullpath}.\"".html_safe) and return
  	end
  	@previous_versions = Doc.find_all_by_component(@doc.component, :order => "dev_stage DESC, maj_version DESC, min_version DESC")

  	respond_to do |format|
  		format.html
  		format.json {render json: @doc}
  	end

  end

  def view_guide

  	@guide = Guide.find_by_url(params[:url])
  	@guide.title == "Recipes" && !params[:display_url].nil? ? @recipe_view = true : @recipe_view = false
  	unless @recipe_view == true
  		if user_signed_in?
  			@guide_sections = GuideSection.find_all_by_guide_id(@guide.id, :order => "display_order ASC")
  		else
		  	@guide_sections = GuideSection.find_all_by_guide_id_and_published(@guide.id, true, :order => "display_order ASC")
			end
	  	if params[:display_url].nil?

app/helpers/site_helper.rb
module SiteHelper

	def all_guides
		return Guide.order("title ASC")
	end
	
	def menu_pages(category)
		@menu = MenuItem.find_all_by_category(category, :order => "display_order ASC")
		@pages = []
		@menu.each {|menu| menu.guide_id.nil? ? (@pages << Page.find(menu.page_id)) : (@pages << Guide.find(menu.guide_id))}
		
		return @pages
	end
	
	def landing_page(category)
		page = Page.find_by_category_and_landing_page(category, true)
		if page.nil?
			return "#"
		else
			return genomespace_url(page)
		end
	end
	
	def edit_button(object)
		case object.class.name
		when "Page"
			@path = edit_page_path(object)
		when "Doc"
			@path = edit_doc_path(object)
		when "GuideSection"
			@path = edit_guide_guide_section_path(Guide.find(object.guide_id), object)
		when "Tool"
			@path = edit_tool_path(object)
		when "Post"
			@path = edit_post_path(object)
		when "Highlight"
			@path = edit_highlight_path(object)
		else
			return false
		end
		return (link_to "<small class=\"edit_page_button\">Edit</small>".html_safe, @path, :class => "edit_page_button_link")
	end
	
	def get_newest_content(videos)
		highlight_date = Highlight.order("updated_at").last.updated_at
		post_date = Post.find_all_by_published(true, order: "updated_at ASC").last.updated_at
		# last_video_date = Time.parse(videos.sort_by {|x| Time.parse(x["published"]["$t"])}.last["published"]["$t"])
		arr = [highlight_date, post_date]
		arr.find_index(arr.sort.last)
	end
end

app/views/site/announcements.html.erb
<% @announcements.each do |announcement| %>

	<h1><%= announcement.title %></h1>
	<p class="byline">Posted by: <strong><%= announcement.updated_by %></strong> on <strong><%= announcement.updated_at.strftime("%B %d, %Y at %I:%M%p") %></strong></p>
	<%= announcement.content.html_safe %>
	<hr />
<% end %>

<div class="flickr_pagination">
	<p><%= (page_entries_info @announcements).html_safe %></p>
	<%= will_paginate @announcements %>
</div>

app/views/site/deliverables_report.html.erb
<h1>GenomeSpace Deliverables Report for <%= @quarter %></h1>
<p>This report contains a list of all non-technical deliverables up for approval this quarter.  Items in red have not been approved yet.  You can review the artifacts for each deliverable by clicking the links in the list below.  Next, indicate your approval (yes/no), type your comments and click submit to send in your report.</p>
<%= form_for :report do |f| %>
	<% @open_deliverables = false %>
	<% @deliverables.each do |d| %>
	<div class="deliverable">
		<%= d.completed? ? "<h3 class=\"completed\">".html_safe : "<h3 class=\"incomplete\">".html_safe %><strong><%= d.identifier.blank? ? "" : "#{d.identifier}: " %><%= d.description %></strong></h3>
			<% unless @artifacts[d.id].nil? %>
				<ul>
				<% artifacts = @artifacts[d.id].contents.split("</p>") %>
				<% artifacts.pop %>
				<% artifacts.each do |a| %>
					<li><%= unless a.nil? then a.html_safe end %></p></li>
				<% end %>
				</ul>
				<% if current_user.deliverables_admin? && !d.completed? %>
					<% div_id = "deliverable_#{d.id}" %>
						<%= f.label "deliverable_#{d.id}_completed".to_sym, "Completed?" %>
						<%= f.select "deliverable_#{d.id}_completed".to_sym, options_for_select([["Yes", 1],["No", 0]], d.completed? ? ["Yes", 1] : ["No", 0]) %>
						<div class="inner">
							<%= f.label "deliverable_#{d.id}_approval_comments".to_sym, "Comments" %><br />
							<%= f.text_area("deliverable_#{d.id}_approval_comments".to_sym, :size => "65x4") %><br />
						</div>
						<%= f.hidden_field "deliverable_#{d.id}_approved_by".to_sym, :value => current_user.email %>
						<% @open_deliverables = true %>
					</div>
				<% elsif d.completed? %>
					<p>Approved on: <%= d.updated_at.blank? ? "N/A" : d.updated_at.to_s(:long) %><br />
					Approved by: <%= d.approved_by.blank? ? "N/A" : d.approved_by.split("@").first %><br />
					Approval Comments: <%= d.approval_comments.blank? ? "N/A" : d.approval_comments %></p>
				<% end %>
		  <% end %>
	</div>
	<hr />
	<% end %>
<%= f.hidden_field :deliverable_ids, :value => @deliverable_ids %>
<%= @open_deliverables == true ? f.submit("Approve") : nil %>
<% end %>	
<p><%= link_to "Back", view_deliverables_path %></p>

app/views/site/recipe_instructions.html.erb
<h1><%= @recipe.title %></h1>
<ol>
<% @steps.each do |step| %>
	<li><%= step.inner_html.html_safe %></li>
<% end %>
</ol>

<p><%= link_to "Back", toc_url(@guide, @recipe) %></p>

app/views/site/register.html.erb
<h1>Register for a GenomeSpace account</h1>
<p>Use this form to sign up for a GenomeSpace account.  Once registered, you will be able to log into GenomeSpace from the GenomeSpace User Interface or from any of the GenomeSpace tools.</p>

<%= form_for :account do |f| %>
	<table><tr>
	<td><%= f.label :username %></td>
	<td><%= f.text_field :username, :value => @username.nil? ? nil : @username %></td></tr><tr>
	<td><%= f.label :email %></td>
	<td><%= f.text_field :email, :value => @email.nil? ? nil : @email %></td></tr><tr>
	<td><%= f.label :password %></td>
	<td><%= f.password_field :password %></td></tr><tr>
	<td><%= f.label :password_confirm %></td>
	<td><%= f.password_field :password_confirm %></td></tr>
	</table>
	<br />
	<%= f.submit "Register" %>

<% end %>

app/views/site/replace_selected_item.js.erb
$("#bboard_window").hide().html("<%= escape_javascript(render(:partial => '/layouts/window_image')) %>").fadeIn(400);

app/views/site/request_received.html.erb
<h1>Thank you for your request</h1>
<h3>Your request has been received. You will receive an email when you are able to register for your GenomeSpace account.</h3>
<%= link_to "Back", site_path %>

app/views/site/search.html.erb
<%= "<h1>Search Results for \"#{params[:search]}\"</h1>".html_safe %>
<%= link_to "Search again on Google #{image_tag('google.png')}".html_safe, google_search_path(params[:search]), class: "google_link" %>
<% unless @results.blank? %>
	<% @results.each do |result| %>
		<div class="result">
		<% case result.class.name %>
		<% when "Page" %>
			<% unless result.team_page? ||  !result.published? || result.dev? %>
				<h3><%= link_to result.excerpts.title.html_safe, result.url %><br />
				<small>/<%= result.url %></small></h3>
				<%= result.excerpts.plain_content.html_safe %>
			<% end %>
		<% when "Doc" %>
			<h3><%= link_to "#{result.excerpts.component.html_safe} (version #{result.get_version})".html_safe, support_docs_url(result) %><br />
			<small><%= support_docs_url(result) %></small></h3>
			<%= result.excerpts.plain_content.html_safe %>
		<% when "GuideSection" %>
			<% unless !result.published? %>
				<% guide = Guide.find(result.guide_id) %>
				<h3><%= link_to "#{guide.title}: #{result.excerpts.title}".html_safe, toc_url(guide, result) %><br />
				<small><%= toc_url(guide, result) %></small></h3>
				<%= result.excerpts.plain_content.html_safe %>
			<% end %>
		<% when "Tool" %>
			<h3><%= link_to "GenomeSpace Enabled Tool: #{result.excerpts.name}".html_safe, gs_tool_url(result) %><br />	
			<small><%= gs_tool_url(result) %></small></h3>
			<%= result.excerpts.plain_content.html_safe %>
		<% when "Highlight" %>
			<% unless result.dev? %>
				<h3><%= link_to result.excerpts.title.html_safe, highlight_url(result) %><br />
				<small>/<%= result.url %></small></h3>
				<%= result.excerpts.plain_content.html_safe %>
			<% end %>
		<% when "Post" %>
			<% unless !result.published? %>
				<h3><%= link_to result.excerpts.title.html_safe, post_url(result) %><br />
				<small>/<%= result.url %></small></h3>
				<%= result.excerpts.plain_content.html_safe %>
			<% end %>
		<% end %>
		</div>
	<% end %>
	
	<div class="center">
		<%= will_paginate @results %>
	</div>
<% else %>
<p>No results were found.</p>
<% end %>

app/views/site/support.html.erb
<h1>Support</h1>
<h2>GenomeSpace Email Forums</h2>
<p>Ask questions, provide feedback, and request new features on the forums. Tool developer forum provides additional news about the early tool adopter program.</p>
<p><%= link_to "Visit GenomeSpace User Forum", "https://groups.google.com/a/broadinstitute.org/forum/?hl=en#!forum/genomespace-users", class: "support_button" %></p>
<p><%= link_to "Visit GenomeSpace Tool Developer Forum", "https://groups.google.com/a/broadinstitute.org/forum/?hl=en#!forum/gs-tool-developers", class: "support_button" %></p>
<h2 class="clear_left">Sign Up</h2>
<p>Enter your email address below and use the check boxes to select which lists you would like to join.  You will receive a confirmation email from each list with instructions on how to complete your regisitration.</p>
<%= form_tag support_google_groups_path do %>
	
	<p><%= label_tag "Email: " %><%= text_field_tag :email, '', :size => 40 %>
	<%= label_tag "GenomeSpace User", "GenomeSpace User" %><%= check_box_tag "genomespace-users" %>
	<%= label_tag "GenomeSpace Tool Developer", "GenomeSpace Tool Developer" %><%= check_box_tag "gs-tool-developers" %>
	<%= submit_tag "Submit" %>
	</p>
<% end %>
<hr />
<h2>Twitter</h2>
<p><%= link_to "#{image_tag('/assets/Twitter_logo_blue.png')} Follow @GenomeSpace on Twitter".html_safe, "https://twitter.com/genomespace", class: "support_button" %></p>
<h2 class="clear_left">Blog & News Highlights</h2>
<p>The GenomeSpace team also frequently announces updates, new features, and events on our team blog and news highlights feeds.  Be sure to check both of them to stay up to date on the latest GenomeSpace developments.</p>
<p><%= link_to "View Blog", view_blog_path, class: "support_button" %><%= link_to "View News Highlights", view_highlights_path, class: "support_button" %></p>
<h2 class="clear_left"><a name="contact"></a>Reporting Bugs</h2>
<p>The GenomeSpace team appreciates your feedback. GenomeSpace is still in development, and bug reports will help improve the quality and usability of the software.  Please report bugs to <%= mail_to "gs-help@broadinstitute.org", nil, :encode => "hex" %>.</p>

app/views/site/team.html.erb
<h1>GenomeSpace Team Content</h1>

<p class="center"><%= link_to "View GenomeSpace Project Deliverables", view_deliverables_path, class: "edit_page_button", style: "font-size: 12px;text-decoration:none;" %></p>

<% unless @team_pages.blank? %>
	<% @team_pages.each do |team| %>
		<p><strong><%= link_to team.title, genomespace_url(team) %></strong><br />
		<%= team.desc %></p>
	<% end %>
<% end %>

app/views/site/view.html.erb
<% if @page.showTitle %>
 <h1>
    <%= @page.title %>
    <% if user_signed_in? %>
        <%= current_user.cms_admin? ? edit_button(@page) : nil %>
    <% end %>
 </h1>

<% end %>

<% if !@page.showTitle %>
 <div>
    <% if user_signed_in? %>
            <%= current_user.cms_admin? ? edit_button(@page) : nil %>
        <% end %>
 </div>
<% end %>



<%= @page.dev? ? "<p style='color: red;'>This page is a dev revision.</p>".html_safe : nil %>
<%= @page.content.html_safe %>

<% if @page.title == "PI Call Minutes" %>

	<%= javascript_tag do %>
	
		audiojs.events.ready(function() {
		  var as = audiojs.createAll();
		});
	
	<% end %>

<% end %>

app/views/site/view_highlights.html.erb
<% if params[:url] %>
	<h1><%= @highlight.title %>
	<% if user_signed_in? %>
		<%= current_user.cms_admin? ? edit_button(@highlight) : nil %>
	<% end %>
	</h1>
	<%= @highlight.dev? ? "<p style='color: red;'>This highlight is a dev revision.</p>".html_safe : nil %>
	<%= @highlight.content.html_safe %>
<% else %>
	<% @highlights.each do |highlight| %>
		<h1><%= link_to highlight.title, view_highlights_path(url: highlight.url) %></h1>
		<%= highlight.content.html_safe %>
	<% end %>
	
	<div class="center"><%= page_entries_info @highlights %><br />
	<%= will_paginate @highlights %></div>
<% end %>